# .project metadata for composefs
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Set slack_channels
# TODO: Set identity_type under legal (has_dco, has_cla)
# TODO: Add adopters list (ADOPTERS.md)
# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "composefs"
name: "composefs"
description: "A project that combines Linux kernel features to provide read-only mountable filesystem trees stacking on top of an underlying "lower" Linux filesystem, particularly useful for mounting container images."
type: "project"
project_lead: "alexl" # TODO: AUTO-DETECTED — please verify
# TODO: Set CNCF Slack channel(s)
# slack_channels:
#   - name: "#composefs"
#     primary: true

maturity_log:
  - phase: "sandbox"
    date: "2025-01-21T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/340" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/containers/composefs"

website: "https://github.com/containers/composefs"

artwork: "https://landscape.cncf.io/logos/cncf.svg"

# TODO: Add ADOPTERS.md if your project tracks adopters
# adopters:
#   path: "https://github.com/composefs/composefs/blob/main/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "composefs/composefs"


security:
  policy:
    path: "https://github.com/composefs/composefs/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/composefs/composefs/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/composefs/composefs/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/composefs/composefs/blob/main/CODE-OF-CONDUCT.md"

legal:
  license:
    path: "https://github.com/composefs/composefs/blob/main/COPYING"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/composefs/composefs/blob/main/README.md"

landscape:
  category: "Runtime"
  subcategory: "Container Runtime"

# CLOMonitor Score: 50/100
# Documentation: 67 | License: 75 | Best Practices: 11 | Security: 50
